### ISSUE TITLE
Transaction scope not working?

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [linq2db/LinqToDB.Identity#17]
I have this code

```
 using (var transaction = new TransactionScope())
 {
     IdentityResult result = await userManager.CreateAsync(user, model.Password);
```
Execution goes inside `userManager.CreateAsync`, and freeze. No exception, no result.

**Comment by MaceWindu** [comment]
Do you have stack to determine where it waits?

**Comment by Dmitrij-Polyanin** [comment]
Here is my code

```
using (var transaction = new TransactionScope())
 {
     IdentityResult result = await userManager.CreateAsync(user, model.Password);
     await db.Users.Where(x => x.Id == user.Id).Set(x => x.Link, x => x.Id.ToString()).UpdateAsync();
```

I tried to debug but any times it breakes different points.
Sometimes it goes to  `await db.Users.Where(x => x.Id == user.Id).Set(x => x.Link, x => x.Id.ToString()).UpdateAsync();`
Sometimes brokes inside  `IdentityResult result = await userManager.CreateAsync(user, model.Password);` in different places inside it.

I am not understanding it.

I use Rider for debug and Ubuntu 18.10 to run.

**Comment by Dmitrij-Polyanin** [comment]
I have only this

> System.InvalidOperationException: A TransactionScope must be disposed on the same thread that it was created.
>    at System.Transactions.TransactionScope.Dispose()
>    at SunEngine.Controllers.AuthController.Register(NewUserViewModel model) in /home/okeanij/Projects/SunEngine/SunEngine/Controllers/AuthController.cs:line 139
>    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
>

**Comment by MaceWindu** [comment]
Looks like TransactionScope is not designed for async execution. Microsoft added `TransactionScopeAsyncFlowOption.Enabled` to handle it, so you should try it first

https://weblogs.thinktecture.com/pawel/2018/06/entity-framework-core-use-transactionscope-with-caution.html

**Comment by Dmitrij-Polyanin** [comment]
All works fine. Thank you!
Maybe to add this to doc?

**Comment by MaceWindu** [comment]
Will do
